name: "Ludvig security scanner"
description: "Scan for secrets and vulnerabilities"
author: Frode Hus
branding:
  color: purple
  icon: eye
inputs:
  path:
    description: "Path to scan"
    required: false
    default: "."
  customRulesPath:
    description: "Path to custom YARA rules"
    required: false
  level:
    description: "Only report findings above the given level [UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL]"
    default: "MEDIUM"
    required: false
  sarifFileName:
    description: "SARIF file name (enables SARIF generation)"
    required: false
  createRelease:
    description: "Downloads all source assets and builds a distributable .tar.gz package containing rules and vulnerability database"
    required: false
outputs:
  result:
    description: "Scan results"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "-c ${{ inputs.customRulesPath }}"
    - "-p ${{ inputs.path }}"
    - "-l ${{ inputs.level }}"
    - "-s ${{ inputs.sarifFileName }}"
    - "-r ${{ inputs.createRelease }}"
