name: build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Ludvig scan
        uses: frodehus/ludvig-action@main
        with:
          path: "src/"
          level: "MEDIUM"
          sarifFileName: "ludvig.sarif"

      - name: Upload Ludvig scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "ludvig.sarif"